### ISSUE TITLE
Create dca file

### ISSUE THREAD

**Issue by SandroMongelluzzo** [mkolas/discord-soundboard#3]
Hello, is there a way to create .dca files since dca-rs is not available anymore. 
Thank you

**Comment by mkolas** [comment]
Funnily enough I just ported this over to an arm-based device the other day and had to figure out another solution to this exact problem. I was able to use https://github.com/jonas747/dca/tree/master/cmd/dca instead, and just aliased the executable to dca-rs  and it seems to work just fine.
